Fix missing header for Visual Studio
src\lib\OpenEXRUtil\ImfCheckFile.cpp(26): error C2039: "max": is not a member of "std"

Signed-off-by: Transporter <ogre.transporter@gmail.com>