exrcheck/main.cpp: add missing <cstdint>
Without the change build fails on this week's gcc-13 as:

    [ 99%] Building CXX object src/test/OpenEXRTest/CMakeFiles/OpenEXRTest.dir/testInputPart.cpp.o
    openexr/src/bin/exrcheck/main.cpp: In function 'bool exrCheck(const char*, bool, bool, bool, bool)':
    openexr/src/bin/exrcheck/main.cpp:65:15: error: 'uintptr_t' does not name a type
       65 |         const uintptr_t kMaxSize = uintptr_t (-1) / 4;
          |               ^~~~~~~~~

Signed-off-by: Sergei Trofimovich <slyich@gmail.com>